---

- name: Verify
  hosts: all
  gather_facts: no

  tasks:
    - name: check if wrapper installed
      ansible.builtin.stat:
        path: "/usr/local/bin/call_restic"
      register: out
      changed_when: false
      failed_when:
        - not out.stat.exists
